spring.application.name=BillingApplicationCoffeshop

# JDBC URL points to SQLite file
spring.datasource.url=jdbc:sqlite:coffeeshop.db

# Driver class for SQLite
spring.datasource.driver-class-name=org.sqlite.JDBC

# Optional: Hibernate dialect for SQLite (if using JPA)
##spring.jpa.database-platform=org.hibernate.dialect.SQLiteDialect

# Disable DDL auto if not needed
##spring.jpa.hibernate.ddl-auto=update

# Show SQL in console (optional)
##spring.jpa.show-sql=true
